model_name_or_path: /data1/gkm/qwen_ft/model/qwen25_vl

stage: sft
do_train: true

finetuning_type: lora
quantization_bit: 4 
lora_target: all

dataset: club_vl_sft
dataset_dir: /data1/gkm/qwen_ft/datasets
template: qwen2_vl

cutoff_len: 2048
#max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

output_dir: saves/qwen25_vl/qlora/sft
logging_steps: 10
save_steps: 50
plot_loss: true
overwrite_output_dir: true

per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 2.0e-5
num_train_epochs: 10.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

val_size: 0.2
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500